package project1;

public enum TokenType {
    COLON, COLON_DASH, COMMA, LEFT_PAREN, PERIOD, Q_MARK, RIGHT_PAREN,
    MULTIPLY, ADD, STRING, SCHEMES, FACTS, RULES, QUERIES, ID,
    EOF, UNDEFINED, WHITESPACE, COMMENT, EQ, NE, GT, GE, LT, LE;
}
